CESI_CSharp_TPChocolatine/Models/Expression.cs
using System.ComponentModel.DataAnnotations;

namespace CESI_CSharp_TPChocolatine.Models
{
    public class Expression
    {
        [Required]
        public int Id { get; set; }

        [Required]
        public string Original { get; set; }

        [Required]
        public string Regional { get; set; }
        
        [Required]
        [Display(Name = "User")]

        public int UserId { get; set; }
        
        [Required]
        [Display(Name = "Region")]

        public int RegionId { get; set; }
    }
}

CESI_CSharp_TPChocolatine/Models/ExpressionViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace CESI_CSharp_TPChocolatine.Models
{
    public class ExpressionViewModel
    {
        public int Id { get; set; }

        public string Original { get; set; }

        public string Regional { get; set; }

        public User User { get; set; }

        public Region Region { get; set; }
    }
}

CESI_CSharp_TPChocolatine/Controllers/ExpressionsController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using CESI_CSharp_TPChocolatine.Data;
using CESI_CSharp_TPChocolatine.Models;
using System.Collections.Generic;

namespace CESI_CSharp_TPChocolatine.Controllers
{
    public class ExpressionsController : Controller
    {
        private readonly DefaultContext _context;

        public ExpressionsController(DefaultContext context)
        {
            _context = context;
        }

        // GET: Expressions
        public async Task<IActionResult> Index()
        {
            List<Expression> expressions = _context.Expression.OrderBy(m => m.Original).ToList();
            List<ExpressionViewModel> displayedExpressions = new List<ExpressionViewModel>();

            foreach (Expression expression in expressions)
            {
                ExpressionViewModel displayExpression = new ExpressionViewModel();
                displayExpression.Id = expression.Id;
                displayExpression.Original = expression.Original;
                displayExpression.Regional = expression.Regional;
                displayExpression.User = _context.User.Find(expression.UserId);
                displayExpression.Region = _context.Region.Find(expression.RegionId);

                displayedExpressions.Add(displayExpression);
            }

            return View(displayedExpressions);
        }

        // GET: Expressions/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var expression = await _context.Expression
                .FirstOrDefaultAsync(m => m.Id == id);
            if (expression == null)
            {
                return NotFound();
            }

            ExpressionViewModel displayExpression = new ExpressionViewModel();
            displayExpression.Id = expression.Id;
            displayExpression.Original = expression.Original;
            displayExpression.Regional = expression.Regional;
            displayExpression.User = _context.User.Find(expression.UserId);
            displayExpression.Region = _context.Region.Find(expression.RegionId);

            return View(displayExpression);
        }

        // GET: Expressions/Create
        public IActionResult Create()
        {
            var vm = new ExpressionEditModel
            {
                AllUsers = _context.User.OrderBy(m => m.LastName).ThenBy(m => m.FirstName).ToDictionary(x => x.Id, x => $"{ x.LastName } { x.FirstName }"),
                AllRegions = _context.Region.OrderBy(m => m.Name).ToDictionary(x => x.Id, x => $"{ x.Name }")
            };
            return View(vm);
        }

        // POST: Expressions/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Original,Regional,UserId,RegionId")] Expression expression)
        {
            if (ModelState.IsValid)
            {
                _context.Add(expression);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(expression);
        }

        // GET: Expressions/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var expression = await _context.Expression
                .FirstOrDefaultAsync(m => m.Id == id);
            if (expression == null)
            {
                return NotFound();
            }

            ExpressionViewModel displayExpression = new ExpressionViewModel();
            displayExpression.Id = expression.Id;
            displayExpression.Original = expression.Original;
            displayExpression.Regional = expression.Regional;
            displayExpression.User = _context.User.Find(expression.UserId);
            displayExpression.Region = _context.Region.Find(expression.RegionId);

            return View(displayExpression);
        }

        // POST: Expressions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var expression = await _context.Expression.FindAsync(id);
            _context.Expression.Remove(expression);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ExpressionExists(int id)
        {
            return _context.Expression.Any(e => e.Id == id);
        }
    }
}

CESI_CSharp_TPChocolatine/Controllers/UsersController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using CESI_CSharp_TPChocolatine.Data;
using CESI_CSharp_TPChocolatine.Models;
using System.Collections.Generic;

namespace CESI_CSharp_TPChocolatine.Controllers
{
    public class UsersController : Controller
    {
        private readonly DefaultContext _context;

        public UsersController(DefaultContext context)
        {
            _context = context;
        }

        // GET: Users
        public async Task<IActionResult> Index()
        {
            List<User> users = _context.User.OrderBy(m => m.LastName).ThenBy(m => m.FirstName).ToList();
            List<UserViewModel> displayedUsers = new List<UserViewModel>();

            foreach (User user in users)
            {
                UserViewModel displayUser = new UserViewModel();
                displayUser.Id = user.Id;
                displayUser.LastName = user.LastName;
                displayUser.FirstName = user.FirstName;
                displayUser.Region = _context.Region.Find(user.RegionId);

                displayedUsers.Add(displayUser);
            }

            return View(displayedUsers);
        }

        // GET: Users/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.User
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            UserViewModel displayUser = new UserViewModel();
            displayUser.Id = user.Id;
            displayUser.LastName = user.LastName;
            displayUser.FirstName = user.FirstName;
            displayUser.Region = _context.Region.Find(user.RegionId);

            return View(displayUser);
        }

        // GET: Users/Create
        public IActionResult Create()
        {
            var vm = new UserEditModel
            {
                AllRegions = _context.Region.OrderBy(m => m.Name).ToDictionary(x => x.Id, x => $"{ x.Name }")
            };
            return View(vm);
        }

        // POST: Users/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FirstName,LastName,RegionId")] UserEditModel user)
        {
            if (ModelState.IsValid)
            {
                User newUser = new User();
                newUser.LastName = user.LastName;
                newUser.FirstName = user.FirstName;
                newUser.RegionId = user.RegionId;

                _context.Add(newUser);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.User.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            var vm = new UserEditModel
            {
                Id = user.Id,
                LastName = user.LastName,
                FirstName = user.FirstName,
                RegionId = user.RegionId,
                AllRegions = _context.Region.ToDictionary(x => x.Id, x => $"{ x.Name }")
            };
            return View(vm);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FirstName,LastName,RegionId")] User user)
        {
            if (id != user.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(user);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.User
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            UserViewModel displayUser = new UserViewModel();
            displayUser.Id = user.Id;
            displayUser.LastName = user.LastName;
            displayUser.FirstName = user.FirstName;
            displayUser.Region = _context.Region.Find(user.RegionId);

            return View(displayUser);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var user = await _context.User.FindAsync(id);
            _context.User.Remove(user);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserExists(int id)
        {
            return _context.User.Any(e => e.Id == id);
        }
    }
}

CESI_CSharp_TPChocolatine/Controllers/VotesController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using CESI_CSharp_TPChocolatine.Data;
using CESI_CSharp_TPChocolatine.Models;
using System.Collections.Generic;

namespace CESI_CSharp_TPChocolatine.Controllers
{
    public class VotesController : Controller
    {
        private readonly DefaultContext _context;

        public VotesController(DefaultContext context)
        {
            _context = context;
        }

        // GET: Votes
        public async Task<IActionResult> Index()
        {
            List<Vote> votes = _context.Vote.OrderByDescending(m => m.Id).ToList();
            List<VoteViewModel> displayedVotes = new List<VoteViewModel>();

            foreach (Vote vote in votes)
            {
                Expression expression = _context.Expression.Find(vote.ExpressionId);

                ExpressionViewModel viewExpression = new ExpressionViewModel();
                viewExpression.Id = expression.Id;
                viewExpression.Original = expression.Original;
                viewExpression.Regional = expression.Regional;
                viewExpression.User = _context.User.Find(expression.UserId);
                viewExpression.Region = _context.Region.Find(expression.RegionId);

                VoteViewModel displayVote = new VoteViewModel();
                displayVote.Id = vote.Id;
                displayVote.User = _context.User.Find(vote.UserId);
                displayVote.Expression = viewExpression;

                displayedVotes.Add(displayVote);
            }

            return View(displayedVotes);
        }

        // GET: Votes/Create
        public IActionResult Create()
        {
            List<Expression> expressions = _context.Expression.OrderBy(m => m.Original).ToList();
            Dictionary<int, string> formattedExpression = new Dictionary<int, string>();

            foreach (Expression expression in expressions)
            {
                Region expressionRegion = _context.Region.Find(expression.RegionId);
                formattedExpression.Add(expression.Id, expression.Original + " / " + expression.Regional + " (" + expressionRegion.Name + ")");
            }

            var vm = new VoteEditModel
            {
                AllUsers = _context.User.OrderBy(m => m.LastName).ThenBy(m => m.FirstName).ToDictionary(x => x.Id, x => $"{ x.LastName } { x.FirstName }"),
                AllExpressions = formattedExpression
            };
            return View(vm);
        }

        // POST: Votes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,UserId,ExpressionId")] Vote vote)
        {
            if (ModelState.IsValid)
            {
                _context.Add(vote);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(vote);
        }

        private bool VoteExists(int id)
        {
            return _context.Vote.Any(e => e.Id == id);
        }
    }
}

CESI_CSharp_TPChocolatine/Views/Expressions/Create.cshtml
@model CESI_CSharp_TPChocolatine.Models.ExpressionEditModel

@{
    ViewData["Title"] = "Expressions > Ajouter une nouvelle expression";

    var usersList = Model.AllUsers.Select(x => new SelectListItem
    {
        Text = x.Value.ToString(),
        Value = x.Key.ToString()
    });

    var regionsList = Model.AllRegions.Select(x => new SelectListItem
    {
        Text = x.Value.ToString(),
        Value = x.Key.ToString()
    });
}

<h1>Expressions</h1>

<h4>Ajouter une nouvelle expression</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Original" class="control-label">Expression nationale</label>
                <input asp-for="Original" class="form-control" />
                <span asp-validation-for="Original" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Regional" class="control-label">Expression régionale</label>
                <input asp-for="Regional" class="form-control" />
                <span asp-validation-for="Regional" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RegionId" class="control-label">Région d'application</label>
                <select class="form-control" asp-for="RegionId" required
                        asp-items="regionsList">
                    <option value="">(Sélectionnez une région...)</option>
                </select>
                <span asp-validation-for="RegionId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserId" class="control-label">Votre nom et prénom</label>
                <p class="small">Si vous ne vous trouvez pas dans la liste, <a asp-area="" asp-controller="Users" asp-action="Create">cliquez ici pour vous inscrire</a>.</p>
                <select class="form-control" asp-for="UserId" required
                        asp-items="usersList">
                    <option value="">(Sélectionnez un utilisateur...)</option>
                </select>
                <span asp-validation-for="UserId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Ajouter l'expression" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Retour à la liste</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CESI_CSharp_TPChocolatine/Views/Expressions/Delete.cshtml
@model CESI_CSharp_TPChocolatine.Models.ExpressionViewModel

@{
    ViewData["Title"] = "Expressions > Supprimer une expression";
}

<h1>Expressions</h1>

<h3>Êtes-vous sûr(e) de vouloir supprimer cette expression ?</h3>
<div>
    <h4>Expression</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Expression nationale
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Original)
        </dd>
        <dt class="col-sm-2">
            Expression régionale
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Regional)
        </dd>
        <dt class="col-sm-2">
            Région d'application
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Region.Name)
        </dd>
        <dt class="col-sm-2">
            Ajoutée par
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.User.FirstName) @Html.DisplayFor(model => model.User.LastName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Retour à la liste</a>
    </form>
</div>

CESI_CSharp_TPChocolatine/Views/Expressions/Details.cshtml
@model CESI_CSharp_TPChocolatine.Models.ExpressionViewModel

@{
    ViewData["Title"] = "Expressions > Détail d'une expression";
}

<h1>Expressions</h1>

<div>
    <h4>Détail d'une expression</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Expression originale
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Original)
        </dd>
        <dt class="col-sm-2">
            Expression régionale
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Regional)
        </dd>
        <dt class="col-sm-2">
            Région d'application
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Region.Name)
        </dd>
        <dt class="col-sm-2">
            Ajoutée par
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.User.FirstName) @Html.DisplayFor(model => model.User.LastName)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Index">Retour à la liste</a>
</div>

CESI_CSharp_TPChocolatine/Views/Expressions/Index.cshtml
@model IEnumerable<CESI_CSharp_TPChocolatine.Models.ExpressionViewModel>

@{
    ViewData["Title"] = "Expressions > Liste des expressions";
}

<h1>Expressions</h1>

<p>
    <a asp-action="Create">Ajouter une nouvelle expression</a> - <a asp-area="*" asp-controller="Votes" asp-action="Create">Voter pour une expression</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Expression nationale
            </th>
            <th>
                Expression régionale
            </th>
            <th>
                Région d'application
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model)
{
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Original)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Regional)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Region.Name)
            </td>
            <td>

                <a asp-action="Details" asp-route-id="@item.Id">Détails</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Supprimer</a>
            </td>
        </tr>
}
    </tbody>
</table>